platform :ios, '10.0'
use_frameworks!

target 'DreamhouseAnywhere' do
	pod 'SwiftlySalesforce'
	pod 'SwiftyJSON'
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
end
