platform :ios, '10.0'
use_frameworks!
	

def shared_pods
  pod 'SwiftyJSON'
  pod 'SwiftlySalesforce'
	pod 'SDWebImage'
end



target 'DreamhouseAnywhere' do
	source 'https://github.com/goinstant/pods-specs-public'
  source 'https://github.com/CocoaPods/Specs.git'

	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
	pod 'ServiceSDK/SOS', '1.1.0'
	shared_pods

	target 'DreamhouseKit' do
  	shared_pods
	end

	target 'DreamhouseMessages' do
		shared_pods
	end

	target 'MessagesExtension' do
		shared_pods
	end
end




